### ISSUE TITLE
Response to owner's close connection event

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#113]
Currently the won-node sents no response to owner' close connection event. Therefore, currently the created on won event and updated on won connection is fetched after a fixed timeout instead of inside the callback. As soon as the won-node is implemented to send response to owner' close connection event, the timeout function and its inside should be removed and we should check if the callback's code on owner is working correctly. Also, the handling of a unsuccess response should be implemented in the callback.

**Comment by sbyim** [comment]
deactivating need involves closing connection of the need.
Currently server side functionality for notifying the need that connections are closed is not implemented.
It is also not easy to simulate this with timout, because unlike other methods, we don't have the eventUri of the connection close events.

**Comment by yanapanchenko** [comment]
The last statement is also mentioned in  #246. The rest is already handled, closing.
