### ISSUE TITLE
Ext-Rescal implementation usage

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1152]
> Does the need-attribute matrix (
> https://github.com/researchstudio-sat/webofneeds/blob/master/webofneeds/won-matcher-rescal/src/main/python/tools/tensor_utils.py#L86-L93)
> correspond to the entity-term matrix from Ext-RESCAL (
> https://github.com/nzhiltsov/Ext-RESCAL#usage-examples)? The Ext-RESCAL
> paper (
> https://www.researchgate.net/profile/Nikita_Zhiltsov/publication/260419630_Improving_entity_search_over_linked_data_by_modeling_latent_semantics/links/548f63930cf214269f263b25.pdf)
> only mentions the entity-term matrix as future work, so I'm not sure if I
> understand it. Based on the README it is a matrix of entities to
> attributes, in which attributes are RDF properties. This doesn't seem to be
> useful, so I must be missing something.

**Comment by heikofriedrich** [comment]
Yes thats right, the need-attribute matrix the entity-term matrix from Ext-RESCAL is exactly. If you check the Github page of the ext rescal implementation you can see that this feature is now implemented: https://github.com/nzhiltsov/Ext-RESCAL/blob/master/extrescal.py#L35-L37. 

This extension was also described in this paper: M. Nickel, V. Tresp, H. Kriegel. Factorizing YAGO: Scalable Machine Learning for Linked Data // Proceedings of the 21st international conference on World Wide Web (WWW'2012). - 2012. 
It is mainly an optimization feature for achieving better scalability:

> In its original form, RESCAL doesn’t recognize attributes of entities explicitly
> [...]
> A naıve approach to include attributes in the factorization would be
> to add an additional slice m + 1 for attributes and to apply some form of preprocessing to the attribute values in the data 
> [...] 

> While this handling of attributes can work for small datasets, it is not
> applicable for large-scale learning on the Semantic Web, as it
> would increase the dimensionality of the entity modes dramatically.  
> The main problem associated with this procedure is that attributes 
> are included as true entities, although they never occur as subjects in a relation. 
> Since RESCAL assumes a tensor with frontal slices of size n×n, a huge
> amount of entries would be wasted in the tensor, what in turn would lead to an 
> increased runtime since a significantly larger tensor would have to be factorized. 
> [...] 
> To overcome this problem, we propose to handle attributes by a separate matrix 
> factorization which we perform jointly with the tensor factorization.

**Comment by jindrichmynarz** [comment]
[Nickel 2012](https://pdfs.semanticscholar.org/498c/a0a1f8c980586408addf7ab2919ecdb7dd3d.pdf) (p. 275) uses attributes for datatype properties with literals values. WoN declares attributes to be everything besides the needs, so that even entities that feature as subjects in other relations are included. Moreover, while Nickel 2012 includes property names with the attributes when making entries in the entity-term matrix, WoN does not.

What is the motivation behind these mismatches with the Ext-RESCAL approach?

**Comment by heikofriedrich** [comment]
Until now we had used no other types than the basically three options: an object was either a need (mapped to an entitiy) or a connection (1's in connection slice between two needs) or a literal attribute of a need (mapped to literal attributes). If you consider only such simple types they map quite perfectly to RESCAL. If you want something more sophisticated we should discuss how to realize it in context of a concrete example.

**Comment by jindrichmynarz** [comment]
I think the original RESCAL fits nicely the case when you consider relations represented by object properties. If objects are [RDF referents](https://www.w3.org/TR/rdf11-concepts/#dfn-referent), they can be subjects in other relations. The approach of modelling the relations as tensor slices is natural in that case.

In my case, the needs are often described by concepts from controlled vocabularies. These are represented by RDF referents, which can be subjects in other relations of interest to matchmaking, such as concept hierarchies.

However, I also have datatype properties that describe the entities with literals, such as dates or prices. Since naïve incorporation of the literals as entities, even with some normalization via lemmatization or discretization, would drastically increase the tensor's dimensionality, using them is more natural with the Ext-RESCAL approach that deals with them using a separate matrix.

For simplicity, I'd start with learning from object properties only and then gradually introduce literals.

**Comment by heikofriedrich** [comment]
Sounds good to me. Just want to add that the approach to model entities and attributes in Ext-RESCAL is compatible with the original RESCAL with only one tensor (no attribute matrix). I think in Ext-RESCAL you can just put the attributes you choose in the attribute matrix and keep all the other stuff (maybe in your case RDF referents) in the tensor. Is that right?
