### ISSUE TITLE
Matcher Service shuts down cause sparql rdfstore bigdata cannot be reached

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1229]
Matcher service logs: 
Error querying SPARQL endpoint http://localhost:9999/bigdata/namespace/kb/sparql. SPARQL endpoint must be running at matcher service startup!

Even though another environment variable should be passed to the property 'uri.sparql.endpoint' and overwrite its default value 'http://localhost:9999/bigdata/namespace/kb/sparql' but this does not happen, which is why the bigdata cannot be reached

**Comment by heikofriedrich** [comment]
This was still with:
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

But got broke with:
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

**Comment by heikofriedrich** [comment]
For next jdk version 1.8.0_131 system parameter passing to java spring boot application is also not working as it used to be => there must be something between versions 121 and 131 that causes this but nothing could be found here:  http://www.oracle.com/technetwork/java/javase/8all-relnotes-2226344.html#R180_131

**Comment by heikofriedrich** [comment]
will fix the docker image usage for now to version openjdk:8u131-jdk

**Comment by fkleedorfer** [comment]
Finally fixing this as we migrate to java 11+. 

The reason was that, starting with jdk8u131, java environment variables cannot contain dots. See https://github.com/docker-library/openjdk/issues/135 (thanks @quasarchimaere for making the connection). The solution is to capitalize the variable names and replace dots with underscores, e.g.
`uri.host` becomes `URI_HOST`. Spring will map these environment variables to their lowercased and dot-using version so you don't have to rename your properties in Javaland. 

@heikofriedrich I am sure you are thrilled to learn this is no longer a mystery ;-)

**Comment by heikofriedrich** [comment]
@fkleedorfer @quasarchimaere  Haha thrilled and relieved that this mystery is finally solved! Good job guys 👍
