### ISSUE TITLE
Skeleton Screens (for improved impression of responsiveness)

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1449]
see nr1 of https://medium.com/@owencm/reactive-web-design-the-secret-to-building-web-apps-that-feel-amazing-b5cbfe9b7c50

**Comment by fkleedorfer** [comment]
later.

**Comment by fkleedorfer** [comment]
Soon.

**Comment by fkleedorfer** [comment]
Suggestion:
* [ ] When fetching the need list, make skeleton needs with a empty icon (unless we have all the info to make the icon), and title `Loading data...`, and if possible, it would be good if the whole skeleton need could also look different as a whole from normal needs, either with a different color or a slow glow/no-glow animation 
* [ ] When data for  the need arrives, replace the title and make it look normal
* [ ] While loading the connections, show `Loading connections...` in the second line (where the type - Search/Post/What's Around/etc - is shown otherwise). Ideally, that loading indicator also has the glow animation or different color the skeleton need had.
* [ ] When the connection data is loaded, replace the loading indicator with the need type
* [ ] Bonus: add skeleton connection items that work the same while loading connections so the skeleton need can be expanded.
