### ISSUE TITLE
Matching is too eager 

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1464]
When no location is given, finds almost anything (on integration-test), also very lax even with specified location

**Comment by heikofriedrich** [comment]
@fkleedorfer: I checked the implementation but i cannot find an error. I suspect that the problem is that your need content (description, title ect.) terms dont match any other (active) need content terms on the environment. Then what happens is that all theoretically matchable needs are returned (max 20) all with the same score even if they have nothing in common with your need. There will be no knee detection since the results all have the same score.
