### ISSUE TITLE
tracking call should only be made when new messages arrive

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1518]
Currently, tracking calls to piwik are sent every time a message is loaded - including when a view is refreshed etc. - this results in way too many tracking calls for a conversation

**Comment by sigpie** [comment]
This is probably caused by a change to `window.location.href` every time a conversation is clicked. To identify which conversation to show, `connectionUri` is added to the URL, which is a route change which is logged by piwik. 

To reduce logging, we could either prevent tracking URL changes where only `connectionUri` is added or removed. Alternatively, we could stop tracking URL changes in general, as e.g. sending a new message is tracked via actions anyway.

**Comment by maxstolze** [comment]
Issue solved @sigpie ?

**Comment by sigpie** [comment]
The issue described by @fkleedorfer seems to be fixed - just loading messages does not create additional piwik calls. 

Piwik still logs all URL changes, this includes e.g. opening needs or conversations.
