### ISSUE TITLE
Matches rendering: show 'create', not 'hint' timestamp

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1604]
The matched needs show the time of the match, however, what they should show is the creation date of the respective need. Otherwise, when you post a need, all matches one initially gets are identical, and hence don't convey any useful information at all.

**Comment by fkleedorfer** [comment]
![grafik](https://user-images.githubusercontent.com/551624/39051685-c5fa19a8-44a9-11e8-9eaa-859d17232e5b.png)

**Comment by fkleedorfer** [comment]
However, it bugs me every time I see matches. Not you @quasarchimaere ?

**Comment by quasarchimaere** [comment]
@fkleedorfer, it would bug me more to see two different timestamps being used in listelements at the same position depending on the type of element, this is even more confusing if you sort by lastupdated timestamp anyway (which we do) in order to have the newest connections  ranked top to bottom, so it would not make sense to see a match ranked first with a visible date of "7 years ago" followed by a connect request that has a visible date of "just now",then the list seems confusing and unsorted

and if we take the visible date as sort date we would push all matches to the bottom possibly not being easily accessible to the user (which would be even worse than the first approach)

i think that if we want to get better connections we should factor the need creation date in the matching score (and if we already do we should take it as a bigger factor) that way we could possibly push old needs out of the matches.

**Comment by peacememories** [comment]
One way to go about this is to either substitute the need creation date if the only update on the connection is that it was created, or just not show any update time until an actual update comes in.
Regarding sorting it could make sense to just sort non-updated connections by matcher score, and prefer updated connections, with update descending.

**Comment by peacememories** [comment]
This issue has been inactive for 2 months. Do we have any new insights? Is it still relevant? (I believe it is)
It might be appropriate to either move this to later/soon or reopen this as "make connection timestamps more useful" or similar, if it is not clear how best to do this.

**Comment by peacememories** [comment]
Bumping because of continued inactivity

**Comment by quasarchimaere** [comment]
will close this, issue is stale
