### ISSUE TITLE
Let the User create searches without hint for counterpart

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1679]
i think it would be good to let the user 'subscribe' certain tags or keywords by posting, without exposing the need itself to anybody else, a request on a match could be handled with an adhoc request

**Comment by fkleedorfer** [comment]
Essentially, you want to make the flag `won:NoHintForCounterpart` available. I like the idea but fear its realization. How do we enable this functionality UX-wise without confusing users?

You seem to suggest that this will make people less reluctant to post something. However, keep in mind that a straightforward GUI solution (e.g., 'don't show to others'  - checkbox) may actually make people who want to post more reluctant to do so - the net effect would  be unclear.

Ultmately, I agree, it would be a nice feature.

**Comment by fkleedorfer** [comment]
This idea is connected to the idea that users post general, long-lived needs that represent general interests, for example, 'local biking' (interested in spontaneous bike tours around one's loccation), 'lunch' (interested in joining colleagues for lunch), etc.

In some of such situations, one would like the `won:NoHintForCounterpart`flag, in others, one may want to do the opposite - show others I  would do it, but don't bug me unless the other person actually wants me - e.g. for sports partners, the decision may depend on the athlete's levels matching up, which is more efficient to check for the person who initiates the transaction by posting the concrete need

Also applicable for such situations: a taxonomy of interests/needs, rather than completely free need authoring.

**Comment by m0ru** [comment]
> ```   
> [                                  {search box }                              🔍     ]
> ```
> * [ ] "allow others to see my search(?) and contact me about it"

But i think this is where the search-analogy breaks down a bit. It's more like willhaben's "search agent". maybe something like that, or like "persistent search".

**Comment by fkleedorfer** [comment]
The topic this is actually about is: *exposing matching control to users*. I think that's the way to go. Just like the details we now work on, the matching controls should be set appropriately for the given context, and users should be able to override them

**Comment by quasarchimaere** [comment]
will be implemented by "pure search" #1976, closing this item
