### ISSUE TITLE
"show post details" button issues

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#1742]
the button seems fairly large in mobile view especially with the new shortened captions i think it could def. fit next to the indicators (maybe we shorten the label to show post or even a good icon) in anyway the size of the button and the underlying speechbubble indent of the connection list suggests that the button has a rather ambiguous action 
![screenshot_20180509-203139](https://user-images.githubusercontent.com/8503486/39832813-8e677e9e-53c8-11e8-9c62-96b83f27c490.png)

**Comment by fkleedorfer** [comment]
I agree, especially when there is only one connection, the button seems to open the counterpart, not the own need

**Comment by m0ru** [comment]
@ waffle discussion column tagging: what's the question to be discussed here? :)

**Comment by fkleedorfer** [comment]
We don't really know what the problem is. I think, the problem is that the button is in an area that I associate with the connected needs, not with my need. I've used the interface for a month now and when I want to close a need, I still first click on the right 'v' because it feels like a menu button. Then the expanded need collapses, I remember I have to click the 'show Post Details' button, and then I start over.

**Comment by fkleedorfer** [comment]
Suggestion: Let's move the 'Show Post Details'  button above the horizontal line and only show it when expanded.

**Comment by fkleedorfer** [comment]
Suggestion: Let's remove the horizontal line that separates title from buttons when expanded. That line makes it look like there were two needs and confusion ensues.

**Comment by fkleedorfer** [comment]
ok, too much confusion here. I'll open a new, clearly defined issue
