### ISSUE TITLE
Use simple-textfield for need-title

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#1764]
to get autogrow and small count for remaining characters below

**Comment by quasarchimaere** [comment]
i dont think we should facilitate autogrow for titles, because then we would probably run into multilined titles (which imho we do not want to encourage), another thing is that the current component is written specifically for chat input, so it includes a send button, which we would not need in the title field, therefore we should not use the simple-textfield until the textfield has been separated into its own component without the mandatory "exec" button of course)

**Comment by fkleedorfer** [comment]
This is outdated now
