### ISSUE TITLE
piwik doesnt record actions on matchat.org anymore since 16.05.18

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1816]

**Comment by heikofriedrich** [comment]
![piwik.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5714a67d0019b11300f6d9bf/125516c66e82c728ace21e0d46f89d8d2a89c1e5cdf9ad4cae58f3806b1c65267e54a17e71d6e77abc1a7d560d0d4eac415e5d40faab8e39baa47e21d40854b088270a36d43703aeb9881eba03bd218f4a85bebb8844c1fa70.png)

**Comment by quasarchimaere** [comment]
@m0ru @peacememories could it be that the webpack.config.ts change did this? i see that there were changes to the file a day before the piwik integration, also there seems to be a somewhat weird implementation with isLive as a boolean, that way we will not be able to easily add config files and access them via build parameter, we should extract the buildparam and use the whole value as the configfilename instead of the boolean value that hardcodes to a specific file, if the param is not set then we should link the default.js instead...

additionally we should step away from the code construct in line 68 of said file " `${isLive ? "live" : "default"}.js`" because that way cant find the usage of the respective files easily, and new developers who do not have that much insight wont be able to figure out where and why the config is even used

**Comment by peacememories** [comment]
I feel the indirection (the webpack config decides which config file to load) is better than the previous approach, where the file was copied into place at build time. This meant import paths in the file were written to match its destination and wouldn't resolve in the ide.
