### ISSUE TITLE
Skinning: connecting... icon still red

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1823]
When "reconnecting" after the websocket connection was lost, a 'loading' icon is shown. on owner-green that icon has a red background.

**Comment by quasarchimaere** [comment]
unfortunately this is due to the fact that gifs do not support transparency, therefore we would have to include an image for each skin in the respective color (see topnav.js -> images/spinner/on_red.gif), however due to maintenance issues and the fact that we want to be lazy and not generate gifs for each skin, we should think about changing these "animations" to svg so we are able to use the same coloring-logic as with the other icons

**Comment by quasarchimaere** [comment]
related to  #782

**Comment by quasarchimaere** [comment]
i agrree option 1 svg is the way to go

**Comment by m0ru** [comment]
for reference: 

![image](https://user-images.githubusercontent.com/1730492/42284433-c9c6e78a-7fac-11e8-812b-e650160e9610.png)
![image](https://user-images.githubusercontent.com/1730492/42284454-d99285de-7fac-11e8-88b9-40398491c15c.png)
