### ISSUE TITLE
Parsing problem with geolocation on matchat

### ISSUE THREAD

**Issue by maxstolze** [researchstudio-sat/webofneeds#1830]
![geo_location_error](https://user-images.githubusercontent.com/32457902/40643127-576cbe2a-631f-11e8-87ca-0da4b8a39d25.png)

**Comment by quasarchimaere** [comment]
the problem seems to be that we want to retrieve the data with set prefixes and not with the fully qualified name, however... i am not sure if we can simply change this to retrieving from the fully qualified name, we might need to have a fork or failsafe for when the data is stored within prefixed names

**Comment by quasarchimaere** [comment]
i just saw that even our own created needs have the location set with the fully qualified name, so i will change this accordingly, this should fix the problem
