### ISSUE TITLE
What's around/new is not matched by newer posts

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1844]
With the new What's around approach, those postings only find Needs that are older than them. 

That's a regression bug.

**Comment by quasarchimaere** [comment]
a matcher log would be interesting, i dont feel like i changed the structure or creation of the old whatsaround need, so it seems odd that they dont match anymore, can someone check the structure between the two needs? also maybe the problem lies in the fact that only the 50 or so best or first matches get the hint so if everybody has a whatsaround need now, chances are not every whatsaround need gets the hint.... if thats the case than its not really a regression bug but thats not the point i know

**Comment by quasarchimaere** [comment]
my assumption that not every existing whatsaround need gets a hint from the matcher lies in my experience with the taxibot factory needs, every 15-20 restarts there was a stray taxi factory need (similar to the whatsaround -> no hint for counterpart...) and that caused the newer factory need to starve because the hints from created needs were only sent to the oldest batch of needs (which was particularly bad because they were orphaned and there was no way to close them without our expiration timer)
