### ISSUE TITLE
Sanitize input for ng-bind-html

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1845]
There's an ng-bind-html-occurrence with outside input: the location names in the location picker, in particular their processing in self.highlight. But that's the the only one. This function needs an extra escaping for the strings gotten from nominatim.

**Comment by quasarchimaere** [comment]
i just looked at the highlight method, and although usually highlighting search results is pretty nifty (especially in long texts) i think that we do not need it at all in the search results of a given string because they:
a) should always have some relation to the searchterm (thus every line should be highlighted somewhere)
b) the amount of text and results are limited  to a few elements
and c) the highlight function doesnt work properly anyway since it takes the whole search string and tries to find it within the search result which makes the highlighting obsolete as soon as you enter the streetnumber because the nominatim will have a different syntax anyway

with that said i think we can safely remove the highlighting feature as it will not have much benefit and we would have to sanitize everything.

**Comment by fkleedorfer** [comment]
see also #1786

**Comment by quasarchimaere** [comment]
@fkleedorfer, thx for the linked issue however the sanitation of this issue cant be solved by the approach given in #1786.

in this instance we "need" ng-bind-html so we can wrap a span over a highlighted text (which imho is not necessary, see comment from before) whereas #1786 would parse hyperlinks that are necessary for a good user experience (which should be handled by a preexisting library, like the one @peacememories suggested)
