### ISSUE TITLE
GUI is slow to react.

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1852]
Testing on Nexus 6/Firefox, at least the following actions are painfully slow (several seconds beteween click and GUI react)

* open connection
* post 
* add detail
* search
* connect
... basically anything.

Before we start 'fixing' that we need to be sure we know the actual cause. Possible hypotheses are:
* excessive use of angular observers and ng-repeat: #1104
* too many queries into rdfstore-js
* too many http requests

**Comment by quasarchimaere** [comment]
i try/tried to tackle the issue as follows:
Due to our past research we found that since everything is a single thread in js, we somehow block the gui by rather expensive/long lasting rdfstore functions, thus i focused my research within linkeddata-service.won.js for now

the idea that we are using too many angular observers and ng-repeats is imho not the reason why our gui is lacking behind, because the amount of repeated elements is way too small to have an performance impact, cuz even with angular 1 that performance drop would have caused people to not adapt to angular in the first place (but thats just MY opinion and could be proven wrong of course)

that the problem lies in the many http requests is also misguiding in my opinion since we would see or run into http timeouts if there are too many long running http requests, (usually a browser only does 5 requests synchronously and pushes the pending requests until the running requests have been done)

**Comment by quasarchimaere** [comment]
with that being said i created log entries for most of the methods in linkeddata-service-won.js to get a feel on what is called when and how often, and found out that alot of things are done there... duh....

anyway i found somewhat of a low hanigng fruit within the ensureRdfsMemberArrays method, this method is called recursivly way too many times, as seen in the log excerpt: provided here:

`linkeddata-service-won.js:1546 ensureRdfsMemberArrays  .
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  m
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  m
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  a
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  a
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  s
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  t
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  e
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  r
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  r
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  .
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  m
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  a
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  t
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  c
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  c
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  h
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  a
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  t
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  .
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  o
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  r
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  g
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  g
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  /
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  w
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  w
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  o
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  n
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  /
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  r
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  e
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  s
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  o
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  u
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  r
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  c
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  e
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  /
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  n
2linkeddata-service-won.js:1546 ensureRdfsMemberArrays  e
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  d
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  /
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  v
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  v
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  o
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  f
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  f
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  o
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  w
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  m
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  c
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  n
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  0
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  0
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  n
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  x
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  x
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  9
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  9
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  2018-05-30T15:53:30.325Z
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  2
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  2
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  0
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  1
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  1
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  8
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  8
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  -
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  -
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  0
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  5
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  5
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  -
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  3
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  3
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  0
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  T
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  T
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  1
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  5
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  :
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  5
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  3
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  :
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  3
linkeddata-service-won.js:1546 ensureRdfsMemberArrays  0`

apparently the method gets called for each character of a string too.... i also found that this method or the initial call of itself doesnt seem to serve any purpose because there is no return value and the second parameter is never accessed from the outside (and usually initialized as a new Set()) the first parameter seems to be the same before and after the call (checked via log entry and non equality operator), so i am assuming we can remove this method all together.... HOWEVER our main performance issue is not going removed then, so it is still somewhere else

**Comment by quasarchimaere** [comment]
![performance_with_ensuremethod](https://user-images.githubusercontent.com/8503486/40915242-9ff7f1c4-67fb-11e8-9100-cdad1fa30dff.PNG)
![performance_wo_ensuremethod](https://user-images.githubusercontent.com/8503486/40915243-a0151b3c-67fb-11e8-895b-d27f9d082f96.PNG)

see the two screenshots above, the first is with the ensureLoadedMethod, the second without the method (results are the same)

the performance without is significantly better than with the method (data is 1 whatsaround need with 15matches -> 16 needs that get parsed), also without the method the gui seems to stay responsive even though no elements are present yet (e.g loading indicator, cursor change on hover, clickable elements open etc)

i will create a pull request with that method removed for now because it is a big performance update (half the processing time per need), but i will investigate different issues further as we are not in the clear yet

**Comment by fkleedorfer** [comment]
Sounds like a good first step!

**Comment by fkleedorfer** [comment]
Merged  #1862 but it's not significantly faster on the original problem setup (live with Nexus 6)

**Comment by fkleedorfer** [comment]
I think click-reactions and typing are a bit faster now (typing sometimes was painfully slow even on the laptop).

**Comment by fkleedorfer** [comment]
One thing we can do immediately is prevent loading of archived needs by remembering their uris in localstorage.

**Comment by fkleedorfer** [comment]
And if we take one step back: what causes the impression that the application is slow?
1. initial loading time (until you see something) - that has improved and isn't so bad now.
2. delay when posting: it can take several seconds until the need shows up in the list.
3. slow GUI reactions: you click a button, the app takes long to even show you that you clicked. Sometimes animations are painfully slow, probably slowed down by other activities, such as loading data from the server
4. long delay after logging in while all the data is being loaded

**Comment by fkleedorfer** [comment]
Another, quite important issue is: which needs should we show in the list when someone logs in? And how should we order them? Currently, we show all active ones, and the ordering is not explained (or even clear to me). If we showed fewer items, we would have less of a performance problem.

I see the following options:
* Top N, according to posting/reactivation date
* Top N, according to recent activity on them
* Top N, according to recency of unread events
* Long shot: allow to group needs by topic, and only show topics

Of course, if we do not show all postings, we need to allow forcing to load the other needs

**Comment by fkleedorfer** [comment]
Another problem that adds to the impression of low speed is the handling of the websocket connection and session timeout. Over several sessions, I learned that, to be on the safe side, I have to reload the page after the  websocket crashed - which leads to me waiting again while everything loads. If that situation was handled gracefully (relogin if necessary, reestablishing the ws connection), that would remove a lot of friction. 

Also, the big red bar at the top looks like something went really wrong. Maybe we could use the secondary color for that?

**Comment by fkleedorfer** [comment]
ok, I'll do it

**Comment by peacememories** [comment]
As mentioned in [#1908](https://github.com/researchstudio-sat/webofneeds/issues/1908#issuecomment-396623027) a lot of our GUI sluggishness is specifically bad in Firefox, and has to do with the way we layout our sites.
