### ISSUE TITLE
Fix 'lost connection' problems

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1885]
context: #1872
context:  #1789
context: #898
context: #990

**Comment by fkleedorfer** [comment]
parent of #1872
parent of #1789
parent of #898

**Comment by quasarchimaere** [comment]
to handle this we could simply check the login status within the "reconnecting" watch (messaging-agent.js:419) what we shoulddo is to check for the login status and if we find out the user is not logged in anymore call a logout and present a toast to the users, saying that that has happened "Due to expiration of your connection you need to login again" that way we could be certain that a "reconnect" try is actually working, and if it isnt we will present that to the user as well
