### ISSUE TITLE
Archiving and unarchiving needs does not always propagate back to owner

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#1891]
## How to reproduce:
1. Go to https://matchat.org
2. Create a need
3. Archive the need
4. Unarchive the need
5. Reload the page

### What is expected:
The need shows as active

### What actually happens:
The need shows as inactive

---

This is also sometimes happens when just archiving a need (it then still shows as active), but this is less reliably reproduced.
The reason appears to be cache invalidation on the browser side, as disabling the cache completely fixes seems to fix the problem.

**Comment by fkleedorfer** [comment]
I may have noticed that with What's Around needs, but not with any other needs so far. Could it be that this is limited to What'sX needs?

**Comment by peacememories** [comment]
I have only tested with "normal" needs (I stumpled across this while testing lazy loading of needs) so no, this is not specific to What'sX

**Comment by quasarchimaere** [comment]
since our fetch crawls are usually called simply by a http-get its somehow easy to imagine that the browser or any other layer in between caches the entry, this is even more likely if the called url is not having any parameters... so an "easy" way to fix this would be to include a random parameter in the fetch get, to ensure there is no way that anything would be able to cache these requests.... if this is the case (and the issue is seemingly reproducable now we should see the request as being received from cache within the network tab of the dev-console

**Comment by quasarchimaere** [comment]
one just has to make sure that caching isnt disabled when the dev console is open, a fact that i overlooked quite alot in the past

**Comment by peacememories** [comment]
You could also send appropriate cache headers in the server instead. Setting the correct `ETAG` should be enough.

**Comment by quasarchimaere** [comment]
could be related to #1939

**Comment by peacememories** [comment]
The issue here is that the `/owner/rest/linked-data` endpoint does not send the correct `Cache-Control` and `ETag` headers.
What it needs to do:
1. Send a `Cache-Control: no-cache` and an appropriate `Etag` header, to force the client to revalidate the resource for every request.
2. Handle client `Etag` headers and only send a full response if the tags do not match.

This would of course cause a request for every need even if we have a cached copy. To fetch updated versions in the background I think we would need to start using a Service Worker.
