### ISSUE TITLE
Archiving whatsX needs does not make them inactive

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1939]
Steps to reproduce:
1. create a WhatsX need
2. archive it
3. klick on the 'N Posts unloaded' link

Observe that your old WhatsX need is actually still active

**Comment by quasarchimaere** [comment]
can't reproduce this with the given repro steps, the rdf document for the post is becoming inactive as intended, a reload on the page shows a "archived but not loaded need" -> which is "ok" since we do not know that its a whatsaround need at this particular moment but clicking on it does not load the need into the open needs

i tried this behaviour with both a privateId user as well as a signed up user, both did not show the need again

**Comment by peacememories** [comment]
This looks a lot like the caching bug I've encountered while developing the inactive need lazy-loading. The problem here is, I think, that our server does not send the correct caching headers so the browser caches needs.

**Comment by peacememories** [comment]
Fwiw, I can't reproduce this either

**Comment by fkleedorfer** [comment]
Closed for now
