### ISSUE TITLE
visitor link broken

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1998]
Try for yourself: https://www.matchat.org/owner/#!post/?postUri=https://node.matchat.org/won/resource/need/fkkw8ny9nvy8

**Comment by quasarchimaere** [comment]
just tried to locate the problem, the problem is within send-request.js specifically within the isLoading method ...duh... its because a visitor link accesses the send-request via post.html and therefore does not have a specific connection or counterpart need, so we must adapt the isLoading() method to just check if the post is available and not isLoading and forget the check of the connection and the connected own need (as they might not be there in the forst place) maybe we need to adapt this logic for the visitorlink specifically but afaik we do not need the connection/ownNeed check in the isLoading anyway
