### ISSUE TITLE
enable CORS in our webapps

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#211]
Quite a simple addition to the web.xml file:
http://enable-cors.org/server_tomcat.html

**Comment by fkleedorfer** [comment]
I don't understand how adding the CORS headers breaks signout... Did it somehow disturb the servlet filter chain?

**Comment by sbyim** [comment]
I couldn't investigate that issue any further, because we didn't have the time, but i could look into it again.
but do we need the CORS filter for our owner web app? the owner web app doesn't receive any requests from other origins?

**Comment by sbyim** [comment]
i have now tested with the owner-webapp why it doesn't work.
it seems like that this issue was caused by several factors..

The main cause was the wrong method call in [user-service.js](https://github.com/researchstudio-sat/webofneeds/blob/feat-search/webofneeds/won-owner-webapp/src/main/webapp/app/service/user-service.js#L200)
the logout function calls the $http.post method with one parameter, with the requet url.

but the angularjs documentation for $http.post states that it should also pass data object.
https://docs.angularjs.org/api/ng/service/$http#post

calling the method with one parameter didn't break the whole application, but it had some side effects.

Compared to other user REST requests, namely signin and isSignedIn, which passes the 'user' object, 
Chrome browser somehow 'adds' the 

>
'Origin:http://localhost:8080' 

to the request header.

in comparison, Firefox doesn't add the mentioned line to the header and works fine.

Once the CorsFilter receives the request,
It goes through the Cors Request processing steps shown here. https://tomcat.apache.org/tomcat-7.0-doc/images/cors-flowchart.png

Tomcat CorsFilter categorizes every request into five types.

1. SIMPLE: A request which is not preceded by a pre-flight request.
2. ACTUAL: A request which is preceded by a pre-flight request.
3. RE_FLIGHT: A pre-flight request.
4. NOT_CORS: A normal same-origin request.
5. INVALID_CORS: A cross-origin request, which is invalid.
 
Usually, the signIn, signOut, and isSignedIn calls are of NOT_CORS type(i.e. when 'Origin' is not set in the header), since its calling a resource from the same domain(localhost in the test case), but this wasn't true only for signOut, because the 'Origin' was set. the type was 'INVALID_CORS', which is also the default type of the CorsFilter and led to 403 error. http://grepcode.com/file/repo1.maven.org/maven2/org.apache.tomcat.embed/tomcat-embed-core/7.0.42/org/apache/catalina/filters/CorsFilter.java#CorsFilter.checkRequestType%28javax.servlet.http.HttpServletRequest%29
This also happens because CorsFilter doesn't handle empty contentType header, which is the case of our request.  

Here are the Request Headers of both Firefox and Chrome

1. Firefox
>Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Accept: application/json, text/plain, */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://localhost:8080/owner/
Cookie: SESSION=92f972c1-565a-4ed9-b9a1-4d8b9d71f6e4
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0

2. Chrome
>Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:no-cache
Connection:keep-alive
Content-Length:0
Cookie:SESSION=3d92b28c-8c56-4b39-bb9b-5a49a17e0996
Host:localhost:8080
Origin:http://localhost:8080
Pragma:no-cache
Referer:http://localhost:8080/owner/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36
