### ISSUE TITLE
JSONLD.js Parse Issue Failed to frame need-data

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#2238]
The given link [https://ownerblue.master.matchat.org/owner/#!/post/?postUri=https:%2F%2Fnodeblue.master.matchat.org%2Fwon%2Fresource%2Fneed%2Fesl5xjgbpze2s96w28mb](https://ownerblue.master.matchat.org/owner/#!/post/?postUri=https:%2F%2Fnodeblue.master.matchat.org%2Fwon%2Fresource%2Fneed%2Fesl5xjgbpze2s96w28mb) should display a correct taxi bot offer, but app. our jsonld.js fails to frame it (it used to work at some point)  -> you have to look into the console output otherwise you only see the mainpage as you are redirected to it due to the failed need retrieval

The Error is as follows:

`Failed to frame need-data. https://nodeblue.master.matchat.org/won/resource/need/esl5xjgbpze2s96w28mb Error: Invalid JSON-LD syntax; if an element has the property "@set" or "@list", then it can have at most one other property that is "@index".
    at new JsonLdError (jsonld.js:932)
    at Object.api.expand (jsonld.js:14830)
    at Object.api.expand (jsonld.js:14654)
    at _expandObject (jsonld.js:15151)
    at api.expand (jsonld.js:14763)
    at _callee2$ (jsonld.js:11464)
    at tryCatch (runtime.js:65)
    at Generator.invoke [as _invoke] (runtime.js:303)
    at Generator.prototype.(:8443/owner/anonymous function) [as next] (https://localhost:8443/owner/generated/app_jspm.bundle.js:94199:21)
    at step (jsonld.js:11035)`

issue is in linkeddata-service-won.js ca. line 1077

**Comment by peacememories** [comment]
## The Problem

This seems to be an issue with the included *jsonld* implementation in our [*rdfstore*](https://github.com/researchstudio-sat/webofneeds/blob/master/webofneeds/won-owner-webapp/src/main/webapp/scripts/rdfstore-js/rdf_store.js).

It gets triggered when a need contains rdf data for a list.
A list, in jsonld, is represented like this to distinguish it from the default interpretation of a json array as a set:

```js
{
    "example:somePredicate": {
        "@list": ["a value"]
    }
}
```

The inline implementation of jsonld does not seem to support this format (yet?) and therefore parses it as a blank node when it is loaded into the rdf store:

```
_:b1 example:somePredicate _:b2
_:b2 "@list" "a value"
```

When retrieving the need from the rdf store the data gets converted to jsonld again (this time with the updated version from npm), which "correctly" results in:

```js
[
    {
         "@id": "_:b2",
         "@list": "a value"
    },
    {
        "@id": "_:b1",
        "example:somePredicate": {
            "@id": "_:b2"
        }
    }
]
```

This, however, is not valid jsonld as the spec notes:

> A list object MUST be a JSON object that contains no keys that expand to an absolute IRI or keyword other than `@list`, `@context`, and `@index`.

*https://json-ld.org/spec/latest/json-ld/#lists-and-sets*

## Possible Fixes

Fixing this problem with our current setup would probably mean updating rdfstore. This *might* fix the problem, but it definitely *will* cause a lot of fallout in our current code base, since there are many breaking changes between our (modified) version of rdfstore and the current release.

It seems more feasible to work around the problem until October, when we will hopefully have the time to replace the current solution wholesale.

### Workarounds

* Before framing the data coming from our rdfstore, run it through a custom converter which fixes the blank nodes containing `@list` attributes.

    This would mean writing said converter, and might introduce more bugs if the implementation is not correct

* Do not use any rdf that contains lists.

    Currently we only use lists in our taxi bot need, because `sh:ignoredProperties` is specced to refer to a list. Since we only use the property to refer to `rdf:type` we could work around this by not ignoring the type but requiring "at least one" type, regardless of its value.

**Comment by quasarchimaere** [comment]
i will try and change the shacl constraints with the suggested workaround from @peacememories
