### ISSUE TITLE
header notification counter and number of new events in private link page gets sometimes inconsistent

### ISSUE THREAD

**Issue by sbyim** [researchstudio-sat/webofneeds#231]
As it can be seen in the screenshot,
the header notification for 'hint' events of the need 'sennheiser offer' and actual number of matches in the private link are inconsistent

![header-private-link inconsistencies](https://cloud.githubusercontent.com/assets/5468024/5917412/8b7dc25e-a61c-11e4-9e1f-64a350d36495.PNG)

**Comment by yanapanchenko** [comment]
seems to be because of #233 displaying the wrong connections. If that one is fixed, we need to check if this one still happens

**Comment by yanapanchenko** [comment]
When #233 is fixed, and the right connections are displayed, this will happen anyway. This is because when we get events and update 'unread' objects, we don't veryfy whether the events are originating from a bad (e.g. currently not-available for fetching) need. So whenever the need is matched with such a bad need, this need is countered in the counteres but won't be displayed in the view.

During refuctoring, we should keep this in mind, so that we handle such cases properly.

**Comment by yanapanchenko** [comment]
This is relevant only for the old GUI, the new GUI is designed to not allow such incosistencies, right @m0ru? Should we close this issue?

**Comment by m0ru** [comment]
Addresses issues in the discontinued, old prototype.
