### ISSUE TITLE
Responsive view of suggested matches scrolls past need details

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2359]
Suggested matches automatically scroll down to the hint messages from the matchers. This isn’t a problem on devices with a big enough screen, but for smaller screens, opening a need only displays some messages that look very similar across all suggested needs instead of the more relevant need details. 

![05b516f0-6328-4109-8c88-61dd17a34b4d](https://user-images.githubusercontent.com/32930574/45303704-b5df0500-b516-11e8-9a17-f7e5253728f6.png)

**Comment by quasarchimaere** [comment]
it seems that the same matcher (see icon) is publishing multiple hints (with a different rating and for whatever reason - re-index?) i think we should figure out a way to combine all hint messages of a connection somehow and make them or their respective scores a part of the post info instead of seperate visible messages

**Comment by quasarchimaere** [comment]
added label "design issue" and removed "bug" because it ain't a bug
