### ISSUE TITLE
Missing feedback when entering URIs for suggesting posts

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2443]
When suggesting posts in a conversation, URIs of unloaded needs can be entered to suggest them. Entering a valid URI adds this need to the list of suggestable needs, but might do so out of the visible list - there is no feedback to the user that adding the need worked, instead the URI field is just reset and no need suggestion is added to the conversation.

child of #2525

**Comment by fkleedorfer** [comment]
> but might do so out of the visible list
.. not sure what that means, @sigpie

**Comment by quasarchimaere** [comment]
@fkleedorfer, it means that if you add a valid needUri that is pushed into the list of suggested needs, it might land in a spot of the list that is currently not visible in the view and thus resulting in the "missing feedback"

**Comment by quasarchimaere** [comment]
the real problem here is that i would like to autoselect the added need to ensure that there is enough feedback when the need could be added, but somehow my approach for error catching did not work so i could not autoselect the entered url because it would have been possible to share the needUri "https://www.example.org"

i already have another idea how to fix this, or at least a new approach that could work, so i assign this issue to myself when i am done with the work i am currently doing
