### ISSUE TITLE
"Re:" posts suggested for suggested posts

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2446]
"Re:" posts that are created by ad-hoc connections should not be shown in the list for suggesting a need in a conversation.

child of #2525
requires #2505
requires #2529

**Comment by quasarchimaere** [comment]
we might consider eliminating the needs which are flagged as won:NoHintForCounterpart, these would include all the re: needs and also all the whatsX needs, however we cant be certain if thats not limiting the users range/intention... i would opt to say that NonOwnNeeds with the above mentioned flag should be ommited from sharing, but not all re: needs in general (def. all whatsarounds though)

additionally we might want to think about how we handle posts that have the saod flags on the receiving end of the conversation, since we cant be sure that noone circumvented our limitation via their own ownerapp or ttl message input

**Comment by sigpie** [comment]
whatsX should definitely be excluded, suggesting a whatsX post, connecting to it and then suggesting posts in the new connection causes unexpected button behaviour, like showing the connection state to the suggested post for the person suggesting the post. (also see #2449)

**Comment by quasarchimaere** [comment]
We only exclude whatsX and inactive needs now, as we do not want to get connects to these users or present them to anyone for that matter, anything else should be suggestable (even Personas)
