### ISSUE TITLE
AdHoc created needs partially inherit need details

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2505]
requires #2520
When creating an AdHoc need, that need copies details from the original need. This is currently an issue for locations, as only the location coordinates, but not the human readable name are added to the AdHoc need. This causes an error during location parsing. 

To reproduce: 
1. Create a need with a location
2. With another account, create an AdHoc connection to that need, either via share link or via hint from WhatsX
3. Check the RDF representation of the AdHoc need to see incomplete location information (i.e. the coordinated from the first need, but not the place name)

![location-error](https://user-images.githubusercontent.com/32930574/48151379-6bcd9200-e2c1-11e8-87db-ab066cf96530.png)

**Comment by quasarchimaere** [comment]
there is no need in duplicating the data within the response needs at all, this does not serve any purpose other than clutter, currently we only add certain details anyway (only title, description, tags, location) but instead of figuring out a way to add all the content of the remoteNeed into the seeks of the direct Response need, and adding "Direct Response to...." or "Re: ...." we should simply create the need with an added flag and add the needUri as a responseToNeed detail as well
