### ISSUE TITLE
Reloading with need details visible causes an exception

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2613]
The errors shown below occur when the owner application is reloaded with open need details. To reproduce:

* create a need
* show need details
* reload the page (ctrl+R or F5)

![reload](https://user-images.githubusercontent.com/32930574/50284129-58811b00-0458-11e9-991c-7db99048292a.png)

**Comment by quasarchimaere** [comment]
is it just showing the error in the log right? does the ui and rellad work as intended?

**Comment by sigpie** [comment]
Everything works as intended despite the logged errors.

**Comment by quasarchimaere** [comment]
this happens due to our redirect within configRouting.js -> i think the better way to handle this is to make it only work in one direction namely from visitorview(post/?postUri) to connections view (defaultView) if the post belongs to the user.

we should remove the redirect from configRouting and implement it via a watch within post.js -> execute the redirect whenever a post is loaded and the post isOwned by the user.

that should prevent the superseeding-exception
