### ISSUE TITLE
Invite suggested member to group does not work

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2704]
When you create a group and get suggestions for members, inviting them ('Request') does not work. The webapp shows some kind of error message saying that this did not work.

**Comment by quasarchimaere** [comment]
probably happens because the needs__connect is called and that creates a simple buildConnectMessage without any regard of the corresponding needfacets, (since they are optional params in the buildConnectMessage) we might need to push the correct facets through the action into the message-builder and then it could work
