### ISSUE TITLE
Multiple dropdown implementations, none of them generic

### ISSUE THREAD

**Issue by peacememories** [researchstudio-sat/webofneeds#2712]
There is one (almost) generic dropdown implementation in `covering-dropdown.js`, but it is only used for the main menu, because it uses a single global state variable for its opened-state, causing all instances to open and close in sync.

Required by #2700

**Comment by peacememories** [comment]
@quasarchimaere is it a problem if I move the menu open flag back to local state? Seems like the only way we can reasonably do this with our current setup

**Comment by quasarchimaere** [comment]
@peacememories yes that would be a problem, please do not change this, the mainmenu visibility does not only depend on if the menu has been clicked but also if there are errormessages due to a failed sign in for example, if we change this to local state then we would have to create a watch that changes the state anyway (if login errors are present -> to show the menu or hide the menu when login was successful. just leave the component as is

**Comment by quasarchimaere** [comment]
also i do not at all see this is required by #2700 -> closing this issue

**Comment by quasarchimaere** [comment]
@peacememories, i dont see the point in making a generic dropdown component when the contents of the dropdown, the icon of the dropdown as well as the hide/show states are different in each of the cases, i think its rather overnegineered if we try to generalize components that are so different, granted post-context-dropdown and connection-context-dropdown are similar but the others arent really

**Comment by peacememories** [comment]
Then I guess I'll create a new dropdown component with a new css.
A bit weird, then, that the covering-dropdown *is* generic, but in a way that makes it usable for only one usecase.
