### ISSUE TITLE
Inconsistent scrolling in need detail view

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2735]
Scrolling with an open need behaves oddly, probably due to a lot of nested components being present. Issue can be seen on Chrome on Windows, create a "What's New" need and open a suggested need with a long description or create a need with a lot of content. 

Scrolling down to see all need content works fine, but scrolling up sometimes doesn't work - sometimes it works, sometimes it works only after moving the mouse, sometimes the outer container scrolls instead of the inner container, etc.

**Comment by quasarchimaere** [comment]
has nothing to do with (too) many nestings, is more due to the fact that there are two scrollable areas in the view itself, the scrollable chat messages and the general view (so footer is not always visible or if the connectionlist is longer than the viewport) this might seem off but i would say that the handling of the scrollpriority is default browser behaviour, depending on mouse cursor or focus

**Comment by quasarchimaere** [comment]
i am pretty sure that the scrolling behaviour is handled by the default browser behaviour and afaik scrolling on a page with multiple scrollable elements (on desktop) scrolls the parts "underneath" the cursor first and after the scrolling reached its end (either the top or the bottom) it will then scroll the parent element and so on --> closing this issue
