### ISSUE TITLE
Use attached images / suggest using a cropped version as title image 

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#2811]
![image](https://user-images.githubusercontent.com/1730492/54289632-cba6b300-45a9-11e9-98ab-449253ca3664.png)

There's images. These could be used as title image.

**Comment by quasarchimaere** [comment]
we would need to add a checkbox to indicate "use as title image" in our image-picker (if there are multiple images present) and include a rdf representation within the rdf part of the selected image which should be included by default if only one image is present.

However since we are trying to add a persona Image anyway (profile image for the persona #2279) we would have a sep. detail and therefore could handle the title image/icon more gracefully -> wysiwyg picker (automatic cropping or whatever)
