### ISSUE TITLE
Loading fails for some posts

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2871]
```
Cant parse need, creationDate or lastUpdateDate not set 
Object { "@id": "https://node.matchat.org/won/resource/need/h9bi11ukefs8", "s:object": (2) […], "cert:key": (2) […], "@context": {…} }
parse-need.js:54:6
Handling a holdableFacet-connection within need:  https://node.matchat.org/won/resource/need/h9bi11ukefs8  setting heldBy to heldByUri:  https://node.matchat.org/won/resource/need/ktzbqrcqu8d9
reduce-connections.js:62:8
Received empty graph  
Object { "@context": {…}, "@graph": [] }
  for need  https://node.matchat.org/won/resource/need/ih9rgjnv4cw4 linkeddata-service-won.js:967:10
    getNeed linkeddata-service-won.js:967
    s jsonld.js:10868
    S jsonld.js:10885
    u jsonld.js:11125
Received empty graph  
Object { "@context": {…}, "@graph": [] }
  for need  https://node.matchat.org/won/resource/need/r3hmqqwpi4i7 linkeddata-service-won.js:967:10
Received empty graph  
Object { "@context": {…}, "@graph": [] }
  for need  https://node.matchat.org/won/resource/need/xx9isjdstz7b linkeddata-service-won.js:967:10
Received empty graph  
Object { "@context": {…}, "@graph": [] }
  for need  https://node.matchat.org/won/resource/need/ktzbqrcqu8d9 linkeddata-service-won.js:967:10
Received empty graph  
Object { "@context": {…}, "@graph": [] }
  for need  https://node.matchat.org/won/resource/need/ih9rgjnv4cw4 linkeddata-service-won.js:967:10
Received empty graph  
Object { "@context": {…}, "@graph": [] }
  for need  https://node.matchat.org/won/resource/need/r3hmqqwpi4i7 linkeddata-service-won.js:967:10
Received empty graph  
Object { "@context": {…}, "@graph": [] }
  for need  https://node.matchat.org/won/resource/need/xx9isjdstz7b linkeddata-service-won.js:967:10
Received empty graph  
Object { "@context": {…}, "@graph": [] }
  for need  https://node.matchat.org/won/resource/need/ktzbqrcqu8d9 linkeddata-service-won.js:967:10
Cant parse need, data is an invalid need-object:  
Object { "@context": {…} }
parse-need.js:96:4
Cant parse need, data is an invalid need-object:  
Object { "@context": {…} }
parse-need.js:96:4
Cant parse need, data is an invalid need-object:  
Object { "@context": {…} }
parse-need.js:96:4
Cant parse need, data is an invalid need-object:  
Object { "@context": {…} }
parse-need.js:96:4
Cant parse need, data is an invalid need-object:  
Object { "@context": {…} }
parse-need.js:96:4
Cant parse need, data is an invalid need-object:  
Object { "@context": {…} }
parse-need.js:96:4
Cant parse need, data is an invalid need-object:  
Object { "@context": {…} }
parse-need.js:96:4
Cant parse need, data is an invalid need-object:  
Object { "@context": {…} }
parse-need.js:96:4
messaging-agent.js: checking heartbeat presence:  0  full intervals of 30s have passed since the last heartbeat.
```

**Comment by quasarchimaere** [comment]
seems to happen for this need: https://node.matchat.org/won/page/need/ih9rgjnv4cw4 -> you can check and reproduce by viewing this uri from any postInfo view (does not need to be on live, can be checked locally too)

**Comment by quasarchimaere** [comment]
Ok Here is a more detailed description:
- Accessing the need directly in the url works (https://node.matchat.org/won/page/need/ih9rgjnv4cw4)
- However if you access it via the post view -> you can test this locally with a running owner webapp and just call: https://localhost:8443/owner/#!/post/?postUri=https:%2F%2Fnode.matchat.org%2Fwon%2Fpage%2Fneed%2Fgbr7zttammw the response of the server (in the network tab of the devtools) reveals this resonse:

`<!doctype html><html lang="de"><head><title>HTTP Status 404 ? nicht gefunden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 ? nicht gefunden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;won&#47;WEB-INF&#47;jsp&#47;notFoundView.jsp</p><p><b>Bescrheibung</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.16</h3></body></html>`

Seems to be an issue on the node or a datacorruption in general, i do not know, but maybe we can fix this before we wipe the content due to the renaming (@fkleedorfer is currently working on) otherwise we might lose the reproduction of this bug -> i will set this to prio: high maybe someone else can have a look at it soon.
