### ISSUE TITLE
Two connections between two atoms

### ISSUE THREAD

**Issue by sigpie** [researchstudio-sat/webofneeds#2936]
The situation below can happen when creating a reaction atom. This might be due to the match being found and suggested between creating the reaction need and opening the connection. 

![two_conns](https://user-images.githubusercontent.com/32930574/58028381-e736b880-7b1a-11e9-9560-f07b7fa50736.png)

**Comment by quasarchimaere** [comment]
this might happen due to the following reason, using the screenshot as example data:
- "Looking for a Musician" received a hint to "I'm looking for a band" (but that hint was only sent to that one side, and not to the counterpart)
- "I'm looking for a band!" requested a connection, and since that atom does not know about the connection that was created on the other side, maybe the node created a new one (that behaviour might be a bug, could this be a reason @fkleedorfer?)

**Comment by fkleedorfer** [comment]
For each atom's facet, there should be at most one connection to any othe atom's facet. If there are multiple, it's a bug.

**Comment by quasarchimaere** [comment]
wasn't a bug  just a ux problem
