### ISSUE TITLE
remember public keys

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#297]
in the implementation we don't use the publishing key obtained on first use, but retrieve them every time, this means that we do not yet protect against X with another keys pretending to be Y.

**Comment by yanapanchenko** [comment]
Some clarifications:

1. The implementation part that deals with need-level resource access: yes, the node retrieves the public key of the need every time when the need accesses a linked data resource - but this is OK as it is in accordance with WebID-TLS that we implement for this case. We can, to a certain extend, protect against X with another keys pretending to be Y by requiring that the Y resource and the key of the Y is only available at the https server (as we do now) and we additionally apply the appropriate trust strategy (e.g. trust only the servers that have certificates issued by a Certificate Authority). (currently we use TrustAnyCertificateStrategy in the implementation)

2. The implementation part that deals with owner-node-matcher app level communication, we use TOFU and store the public keys and reject the communication if the key has changed. Which actually can be a problem in future because we didn't account for key revocation/expiration cases so far.
