### ISSUE TITLE
Matcher published as need

### ISSUE THREAD

**Issue by yanapanchenko** [researchstudio-sat/webofneeds#307]
We want to check whether representing matcher as need siplifies our protocol. Such matcher need, e.g. offer_matches need, might have connections to nodes and send 'hint' messages within such connections; the node, at least the node that wants to receive matches for the needs published on it, should also probably be represented as need, e.g. want_matches need).

One benefit would be that the matcher could receive messages in a way consistent with the current protocol, such as hint delivery success/failure responses, and feedback (quality of match) messages.

**Comment by fkleedorfer** [comment]
This requires a 'matcher' facet for needs in order to receive hints. This solves a problem we've had for a long time: sometimes we're not interested in hints (e.g. "direct responses"). With this solution, we just omit the matcher facet.

The handling of hint messages would have to be moved to the implementation of the 'matcher' facet.

**Comment by fkleedorfer** [comment]
Cleaning up old issues. This is definitely an important refactoring we will need in one way or another.
