### ISSUE TITLE
WebSocket only created before login

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#381]
The SockJS WS is only created once before the login, we need to destroy the websocket after a login and create a new one, otherwise the created needs will be owned by an anonymous user

**Comment by m0ru** [comment]
The better solution would be to have the server upgrade the websocket and associate it with the full user account as long as they're logged in (as compared to the anonymous, pre-login account). If spring security makes this impossible to implement feasibly, the next best solution would be to drop the anonymous socket on login, thus forcing the clients to reconnect if necessary with their new session-id. Both of these solutions also avoid inconsistencies between different tabs.

With an eye towards the looming deadline and to avoid changing the server the old gui also runs against at the demo, I'll be implementing a hack. It adds a notification flag to the state (and two actions) to notify the messaging agent that it should reset the connection. All parts of the hack are tagged with a link to this issue. We should remove them asap after the deadline. One remaining bug due to this is, that if one tab logs in, the other one still posts to it's deprecated websocket, thus posting as anonymous.

**Comment by m0ru** [comment]
Hack contained in pull request #382

**Comment by quasarchimaere** [comment]
as far as i know this was fixed, question @m0ru: can we close this?

**Comment by quasarchimaere** [comment]
i will close this issue now, since it is not a problem since 18 of june
