### ISSUE TITLE
Running two owner apps with the same certificates causes problems

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#415]
Steps to reproduce:
1.  run an owner webapp locally (connect to any WoN node)
2.  Create need in owner webapp -> should work
3.  start an EchoBot locally, connect it to the same WoN node
4.  Create another need in owner webapp -> hangs in create view
   Suspicion: this is due to the bot and the owner webapp using the same certificate

**Comment by fkleedorfer** [comment]
@m0ru please confirm if using different certificates for bot and owner webapp fixes this

**Comment by yanapanchenko** [comment]
Bot and owner should use different certificate, and also only one bot at a time may run. This is because the queues in messaging for owner (and bot acts as owner) correspond to their certificates. So practically when the 2 different owner acting entities use the same certificates they read messages from node from the same queue. Therefore it can happen that a message intended for entity 1 (e.g. success response) is consumed by entity 2 and entity 1 will never get it.

**Comment by m0ru** [comment]
@fkleedorfer yep. i have an extra set of keys for the echo bot atm (and a second copy of our config-directory pointing to these keys). however this is a rather cumbersome setup as i need to apply any changes in the config to both of these. i don't know how we could structure this better, though. :|

**Comment by quasarchimaere** [comment]
using different conf folders fixes this -> no longer relevant

**Comment by quasarchimaere** [comment]
also duplicates #415
