### ISSUE TITLE
Load data selectively

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#623]
Instead of loading everything  on startup, determine what needs to be loaded and load only that.

**Comment by m0ru** [comment]
I think we should really break this down in seperate tasks and merge work on them into a `feat_load_selectively` branch.

 A breakdown of steps might be as follows:

1. Chat messages: only load when the connection is opened.
1. Chat messages: 
  * only load latest 10 messages
  * "see more"-action
  * spinning-wheel while it's loading
1. in the list-view: load matches/requests/conversations of a post only when it's folded-out
1. in the list-view:
  * only load the first 10
  * "see more matches/requests/conversations"-action
  * spinning-wheel while it's loading
1. in the grid/tiles view for matches:
  * only load the latest 10 matches *over all needs*
  * "see more"-action
  * spinning-wheel while it's loading
1. post-overview
  * only load 10 posts with the newest updates (where unread(?) messages trump unread(?) requests trump matches)
  * "See more posts"-action
  * spinning-wheel while it's loading
1. feed:
  * load 5 posts with the latest events – and 3 of the latter for each – with prioritization/sorting as specified above 
  * "see more events"-action for a given post
  * "see more posts"-action
  * spinning-wheels in all of the above places while they're loading

These intereactions should be introduced as new action-creators that load the data and then dispatch new actions of those new action-types. Some of these actions are triggered by clicks on the "more"-links, some by scrolling (e.g. in the feed)

The spinning wheels can be created by tagging the ownNeeds/post/connection-objects in the state with a `isFetchingMore` boolean.

**Comment by m0ru** [comment]
Goal: have as few requests as possible.
 
Only load info that's relevant atm. E.g. skip closed connections / needs u

**Comment by m0ru** [comment]
The bottle-neck atm: the crawling on the server: 
![unbenannt](https://cloud.githubusercontent.com/assets/1730492/16809833/0737e484-4922-11e6-9830-5bddb1ba5c3a.PNG)

counterparts and events that aren't included in the deep request:
![unbenannt](https://cloud.githubusercontent.com/assets/1730492/16809854/173a8ac6-4922-11e6-8c53-68ef7f04dba5.PNG)

**Comment by m0ru** [comment]
Two different goals:
* As few requests as possible (which is important on low-bandwidth networks)
* minimal crawling effort on server (use the paging feature)

**Comment by m0ru** [comment]
Searching for solutions:

* [redux-api-middleware](https://github.com/agraboso/redux-api-middleware) takes care of making http requests and dispatching the results as actions. Probable not useful for as, as most http-requests are made via the linked-data specific utilities in `won.js` and `linkeddata-service-won.js` that utilize a client-side rdfstore in the background.

**Comment by m0ru** [comment]
Other thoughts: 

* The `fetching`-flags should be true in the initial state.

**Comment by m0ru** [comment]
It probably would make sense to start with the feed as pain-points will show up there first anyway.

**Comment by m0ru** [comment]
Documentation for our [linkeddata-paging API](https://github.com/researchstudio-sat/webofneeds/blob/b97645fe5605c665712427ae9510618e3ff131b6/webofneeds/won-node-webapp/doc/linked-data-paging.md)

**Comment by m0ru** [comment]
#749 introduces the necessary code in `won.fetch`. However several parameters don't work yet (e.g. `deep` for event-containers, `type`, `timeof`), but at least they can be more easily tested now.

**Comment by m0ru** [comment]
The notes I took while discussing this issue with @fkleedorfer:

---

## Misc

most difficult cases "only load 10 posts with the newest updates" and "last 10 matches over all needs"

owner has to cache need info (e.g. what has been seen, when the last updates of which type has happened, etc) necessary to implement "only load 10 posts with the newest updates".

does this ultimatively require the owner to cache the entire node-state for that user? how to avoid huge startup-cost, i.e. loading needs for every user? don't load data for users that haven't logged in for a while? only load delta since last poll?

client-to-server = marking things as seen: POST list of eventUris
server-to-client: bloom-filter? list of unread uris (might be long)? list of latest unread + aggregated numbers? a special message if another client-instance marks the event as seen?

When previous requests have been finished and no new action triggered, the client could load preemptively -- e.g. load connection with new unread events (as they might grab the users attention) or after the list of conversations has finished loading, start fetching the first few conversations. We just need to make sure, user-triggered actions always have precedence. The agent can publish multiple actions for each of these loaded data-packages.

Most of the loading should happen through the more declarative  **construct queries**!!

always use `deep=true` to resolve collections

Note that "the last 10 events" (N) isn't the same as "the last 10 events the user gets to see" (N'), the difference for example being success messages. Until the server-API reflects this issue, `N = 3 * N'` can be used.

## architectural approaches on the client:

* Complex agent that looks at the route and the data already loaded and fetches missing data as required.
  * agent that makes sure data is loaded based on route. split agent and put depenendency info into components (`getRequiredData`)? nvm, "only load latest" is a seperate concern -- the components should only deal with translating state to html.
  * Generic load-action? kinda makes redux pointless or duplicates the information for how the state should look like. unless the load action can use a wide range of payload structures and the reducers can deal with all of them.
* Elm-style reducer that produce commands + generic fetch-agent? `(action, state) → (cmd, state')` as opposed to `(action, state) → state'`
  * see agent for generic points
  * Can we replace our current action-creators with these? The ACs contain far too much logic for something that should just encapsulate side-effects. 
  * Atm the messaging-agent breaks the single responsibility principle quite a bit. It should only be a *thin* binding layer between the websocket and redux – and *not* do any parsing.
  * commands: 
    * `construct_query` + query + paging-parameters
    * `getNode` /  `getNeed` + paging-parameters
    * `fetch` + params
* FB data-centric apps architecture? components with construct-queries + things-to-load? successive accumulate queries for nested components.


## Caching

quick'n'dirty: always reload if the params differ from previous params

the events received via the websocket should be pushed to the rdf-store, including `rdfs:member` entries, and they should be marked as cached.

if dirty: only load beginning with *latest* member automatically to avoid unnecessary server-load.

selective loading and caching:

* "last 10": reload anyway
* "last 10 @ time_1": reload if time_1 > time_0 (+c ?)
* "TYPE": only load if this type hasn't been loaded yet
* "resumebefore x1": load if x1 is newer than x0
* "resumeafter x1": always load
* …

But actually we shouldn't need this smart caching as we get all necessary information through the web-socket. Everything should be either initially fetched at page-load or in case the user clicks "more" be connections/events older than the previously oldest uri – thus a cache-miss anyway. We could implement checks as the ones above to detect non-well-behaved code though. The only exception is connection-messages we send ourselves, that we need to invalidate and fetch after posting to get the timestamps from our owner. 

---

**Comment by m0ru** [comment]
Note: the `won.deleteNode(uri)` somewhere around [`linkeddata-service-won.js:~790`](https://github.com/researchstudio-sat/webofneeds/blob/dae7527b6f8c8c5ef920a744f5254eab27a4a0c7/webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js#L788) might be problematic, as in it's current form it deletes the entire container when fetching a new page.

**Comment by m0ru** [comment]
Here's an example redux-app that uses pagination (on github-API content): <https://github.com/reactjs/redux/tree/master/examples/real-world>

**Comment by m0ru** [comment]
The following relay-example on paging might provide inspiration on how to embed crawlable queries in components: <https://www.reindex.io/blog/redux-and-relay/#relay-4>

**Comment by m0ru** [comment]
For the decisions:

* the Elm-Architecture would need too much refactoring right now or introduce another style and thus increase the complexity of the code-base.
* the agent would require to specify the data-dependencies twice or traverse the currently visible component tree on every update. Also it can only look at the state, in particular the routing parameters, not actions (e.g. a person clicking on "Show more" or scrolling down)

Thus the loading will continue to happen in asynchronous action-creators. But instead of having one automatic call as part of the page-load, the components will call some kind of `requestData`-AC every time (additional) data is required, e.g. while the component is initialized, a critical routing parameter changes or when a person requests more data. These action-creators should be kept as small as possible, though!

**Comment by m0ru** [comment]
Spinners! #782

**Comment by m0ru** [comment]
There's a spaghetti-code snippet in the branch, that makes sure all events of the connection are loaded whenever the conversation is accessed (I'll refactor it to conform to the architecture specified above, once all edge-cases have been found).

One of these problems: Unless all queries to a connection pass along the paging-size, all event-uris get loaded into the rdfstore. Followingly, all queries that go on to load all referenced events will then load all events. Even if a paging-size was specified for the query. This will be a tough one to avoid:

* Make all crawlableQueries using a paging-size use a temporary rdfstore first and only recurse among the triples contained therein. The obvious downside is, that always *everything* in the query will be loaded again, e.g. also the connection when querying for connection plus events.
* Make the executeCrawlableQuery aware of how paging works on the backend, so it only recurses into the nodes the server would have returned. That would mean two implementations which must be kept perfectly idempotent.

**Comment by m0ru** [comment]
The connectionMessages gotten via the websocket should be added to the rdf-store as well (including a "made-up" `rdfs:member` triple)

**Comment by quasarchimaere** [comment]
pretty sure we can close this, since we implemented some of that with the skeleton screens and so on, i think this issue is obsolete now, or should be boiled down to something more specific (as its own issue) @fkleedorfer if you agree please close this issue

**Comment by quasarchimaere** [comment]
closing this, if we need to do more we will create separate issues for it
