### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#627]
Currently entering html/script content as chatMessages is only prevented client side (thus trivially circumventable).

As it's possible to run rogue nodes, everything received from them should be assumed unsafe and sanitized, e.g. all embedded html/scripts stripped!

**Comment by m0ru** [comment]
To clarify the issue: someone needs over all occurrences of `ng-bind-html` (i.e. unescaped template interpolations) and check if there's any content from the node that get's used in these.

**Comment by quasarchimaere** [comment]
the point is why do we, or would we even have ng-bind-html to display user content afaik we do not do this, especially in text messages

**Comment by peacememories** [comment]
I feel this is best solved by correctly rendering messages in the view layer instead of trying to sanitize input.
1) This allows us to change the sanitization rules afterward, without either having to rerun our sanitizer or losing data
2) It keeps our node/owner from getting to complicated while allowing the client to even deal with malicious owner servers.

**Comment by m0ru** [comment]
There's an `ng-bind-html`-occurrence with outside input: the location names in the location picker, in particular their processing in `self.highlight`. But that's the the only one.

This function needs an extra escaping for the strings gotten from nominatim, then this issue can be closed.

**Comment by fkleedorfer** [comment]
ok. That one occurrence of `ng-bind-html`will be a separate issue. closing this one
