### ISSUE TITLE
standard login page

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#814]
A user wants: 
"A real \"login\" page for Web Of Need web site in order to automatise login with password manager (like 1Password)"

**Comment by m0ru** [comment]
To enable auto-complete, making it a `<form>` -- instead of a `<div>` -- was enough.

Auto-fill is a bit trickier. Some browsers/plugins -- e.g. firefox/keefox -- don't trigger an input-event when filling.  Thankfully there's people who've dealt with that problem before:

* <http://victorblog.com/2014/01/12/fixing-autocomplete-autofill-on-angularjs-form-submit/>
* <http://stackoverflow.com/questions/21168367/angularjs-chrome-autocomplete-dilemma>

**Comment by m0ru** [comment]
The easiest solution seems to trigger input events on the email- and password-field when the login form is loaded and when it becomes visible (to catch all auto-fill strategies)

**Comment by m0ru** [comment]
Fixed so far with the pull-request. There's still an issue, if someone opens the login form faster than the page finishes loading (auto-fill triggers only then, at least for FF+Keefox). There's a additional waves of updates 500ms, 1s and 2s after the login-form has finished. Hopefully the page has finished loading by then, but the user not clicked on the sign-in button. Hopefully mozilla fixes this behaviour soon.
